#### Interpolación Numérica

Nuestro objetivo de la lección será el obtener datos de puntos que estén entre otros dados. O también hacer pasar funciones por ciertos puntos dados.

Las funciones más simples que podemos hacer pasar por puntos dados son las funciones polinomiales.

Dados $n+1$ puntos queremos hacer pasar un polinomio de grado $n$ por esos puntos.

¿Como podemos hacer que por esos $n+1$ puntos pase un polinomio de grado $n$?

Inspiremonos de la recta $ax+b$
$$\begin{bmatrix} x_1&1\\x_2&1\end{bmatrix}\begin{bmatrix}a\\b\end{bmatrix}=\begin{bmatrix}y_1\\y_2\end{bmatrix}$$

El valor de $a$ y $b$ queda completamente determinado resolviendo el sistema y tiene una unica solución si $x_1\neq x_2$

Nuestra primera idea sería construir una matriz
$$\begin{bmatrix}x_1^{n-1}&...&x_1^0\\\vdots &...&\vdots\\ x_n^{n-1}&...&x_1^0\end{bmatrix}\begin{bmatrix}a_1\\\vdots \\a_n\end{bmatrix}=\begin{bmatrix}y_1\\\vdots \\y_n\end{bmatrix}$$

Entonces los coeficientes del polinomio están dados por los valores de $(x_1,y_1),...,(x_n,y_n)$

Y la solución es única si $x_i\neq x_j$ para $i\neq j$

Veamos como podemos hacer pasar un polinomio por dichos puntos

In [66]:
import numpy as np
def PoliInt(x,y):
    n=len(x)
    A=np.zeros((n,n))
    for i in range(n):
        A[:,n-1-i]=x**i
    print(A)
    a=np.linalg.solve(A,y)
    return a      

Ej: veamos la recta que pasa por los puntos $(x_1,y_1)=(1,2)$ y $(x_2,y_2)=(3,-1)$

In [64]:
x=np.array([1,3])
print(x)
y=np.array([2,-1])
y

[1 3]


array([ 2, -1])

In [67]:
PoliInt(x,y)

[[1. 1.]
 [3. 1.]]


array([-1.5,  3.5])

In [68]:
-1.5*x+3.5

array([ 2., -1.])

Podemos hacerlo tranquilamente para cualquier grupo de puntos que tengan en valores en $x$ diferente.

Ej: Que pase por los puntos $(0,-1)$, $(-1,-6)$,$(1,4)$, $(2,27)$

In [69]:
x=np.array([-1,0,1,2])
y=np.array([-6,-1,4,27])


In [70]:
PoliInt(x,y)

[[-1.  1. -1.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]]


array([ 3.,  0.,  2., -1.])

El polinomio es $3x^3+2x-1$

Podemos hacer para cualquier valor aleatorio. 

Tarea: Darse 4 puntos y calcular el polinomio de interpolación. 

#### Metodo de Lagrange


Vamos a considerar las funciones
$$l_i(x)=\left\{\begin{array}{rcl}0, &x=x_j, j\neq i\\ 1, &x=x_i \end{array}\right.$$

Las funciones que hacen esto son
$$l_i(x)=\prod_{j=0, j\neq i }^n\frac{x-x_j}{x_i-x_j}$$

Rem: Para todos los valores $x_j$ tenemos 
$$l_i(x_j)=0$$
y 
$$l_i(x_i)=1$$

La idea de Lagrange es muy sencilla, simplemente sumamos estas funciones características de Lagrange y la unica que va a importar en un punto $x_i$ dado será $l_i$ y en consecuencia basta multiplicar por $y_i$ para hacer que el polinomio pase por el punto $(x_i,y_i)$

Es decir que la formula de Lagrange será
$$p(x)=\sum_{i=0}^n l_i(x)y_i$$

In [1]:
import sympy as sy

In [2]:
x=sy.symbols('x')

In [3]:
l0=(x+1)*(x-1)*(x-2)/(0+1)/(0-1)/(0-2)
l0

(x - 2)*(x - 1)*(x + 1)/2

In [5]:
sy.expand(l0)

x**3/2 - x**2 - x/2 + 1

Nuestro primer polinomio característico de Lagrange es  
$$l_0(x)=\frac{x^3}{2}-x^2-\frac{x}{2}+1$$

In [6]:
l1=(x-0)*(x-1)*(x-2)/(-1-0)/(-1-1)/(-1-2)
l1

-x*(x - 2)*(x - 1)/6

In [7]:
sy.expand(l1)

-x**3/6 + x**2/2 - x/3

In [8]:
l2=(x-0)*(x+1)*(x-2)/(1-0)/(1+1)/(1-2)
l2

-x*(x - 2)*(x + 1)/2

In [9]:
sy.expand(l2)

-x**3/2 + x**2/2 + x

In [11]:
l3=(x-0)*(x+1)*(x-1)/(2-0)/(2+1)/(2-1)
l3

x*(x - 1)*(x + 1)/6

In [12]:
sy.expand(l3)

x**3/6 - x/6

Tenemos entonces
$$l_1(x)=-\frac{x^3}{6}+\frac{x^2}{2}-\frac{x}{3}$$
$$l_2(x)=-\frac{x^3}{2}+\frac{x^2}{2}+x$$
$$l_3(x)=\frac{x^3}{6}-\frac{x}{6}$$

El polinomio de interpolación será entonces
$$p(x)=l_0(x)(-1)+l_1(x)(-6)+l_2(x)(4)+l_3(x)(27)=$$

In [14]:
p=l0*(-1)+l1*(-6)+l2*4+l3*27
p

x*(x - 2)*(x - 1) - 2*x*(x - 2)*(x + 1) + 9*x*(x - 1)*(x + 1)/2 - (x - 2)*(x - 1)*(x + 1)/2

In [16]:
sy.expand(p)

3*x**3 + 2*x - 1

¿Dados $n$ puntos, el polinomio de interpolación de grado $n-1$ que pasa por dichos puntos es único? 

La respuesta es que bajo esas condiciones el polinomio de interpolación es único, es decir que no importa el método que utilicemos, si los puntos están dados el polinomio está completamente determinado.

Probemos la afirmación anterior

Sean $p_1(x)$ y $p_2(x)$ dos polinomios de grado $n-1$ que pasan exactamente por $n$ puntos dados.
Vamos a considerar 
$$P(x)=p_1(x)-p_2(x)$$
De manera obligatoria tenemos
$$P(x_i)=p_1(x_i)-p_2(x_i)=y_i-y_i=0$$

Es decir que tenemos $n$ raices de $P(x)$ (todos los $x_i$), pero $P$ es un polinomio de grado $n-1$ y por lo tanto tiene $n-1$ raices.

Lo anterior es imposible salvo que 
$$P(x)=0, \forall x$$

Y por lo cuál $p_1(x)=p_2(x)$

#### Método de Newton


el método de Newton es constructivista, es decir que vamos a ir aumentando grado por grado hasta alcanzar los valores deseados

$$p_0(x)=y_0$$
Este polinomio constante pasa por el punto $(x_0,y_0)$

Si $p_{n-1}(x)$ pasa por los puntos $(x_i,y_i)$ para $i=0, ...,n-1$ entonces 

$$p_n(x)=p_{n-1}(x)+c\prod_{i=0}^{n-1}(x-x_i)$$

Rem: 
$$p_n(x_i)=y_i, i=0, ...,n-1$$

Y para hacer que pase por el punto $(x_n,y_n)$ debemos escoger la constante $c$ de tal forma que haga pasar exactamente por el punto deseado
$$c=\frac{y_n-p_{n-1}(x_n)}{\prod_{i=0}^{n-1}(x_n-x_i)}$$

Para nuestro ejemplo tenemos
$$p_0(x)=-1$$
$$p_1(x)=p_0(x)+c_1(x-0)$$
De donde 
$$c_1=(p_1(-1)-p_0(-1))/(-1-0)=\frac{-6-(-1)}{-1}=5$$

Y tenemos
$$p_1(x)=-1+5x=5x-1$$

Ahora podemos hacer para $(1,4)$
$$p_2(x)=p_1(x)+c_2(x-0)(x+1)$$

De donde 
$$c_2=\frac{p_2(1)-p_1(1)}{(1-0)(1+1)}=\frac{4-4}{2}=0$$

Es decir que 
$$p_2(x)=p_1(x)+0(x-0)(x+1)=p_1(x)=5x-1$$

Ahora para el  último punto $(2,27)$
$$p_3(x)=p_2(x)+c_3(x-0)(x+1)(x-1)$$
 y tenemos
$$c_3=\frac{p_3(x)-p_2(x)}{x(x+1)(x-1)}=\frac{27-9}{2*3*1}=3$$

y de donde 
$$p_3(x)=p_2(x)+3x(x^2-1)=5x-1+3x^3-3x=3x^3+2x-1$$

Veamos otro ejemplo 
* $(-2,8)$, $(-1,5)$, $(0,2)$ y $(1,5)$

Tenemos 
$$p_0(x)=8$$

$$p_1(x)=p_0(x)+c_1(x+2)$$

Identificamos $c_1$
$$c_1=\frac{p_1(x_1)-p_0(x_1)}{x_1+2}=\frac{5-8}{-1+2}=-3$$
Por lo cual
$$p_1(x)=p_0(x)-3(x+2)=8-3x-6=2-3x$$

Ahora 
$$p_2(x)=p_1(x)+c_2(x+2)(x+1)$$
y de donde 
$$c_2=\frac{p_2(x_2)-p_1(x_2)}{(x_2+2)(x_2+1)}=\frac{2-2}{2}=0$$

Y por lo tanto
$$p_2(x)=p_1(x)+0(x^2+3x+2)=2-3x$$

Y finalmente tenemos
$$p_3(x)=p_2(x)+c_3(x+2)(x+1)(x-0)$$

De donde
$$c_3=\frac{p_3(x_3)-p_2(x_3)}{(x_3+2)(x_3+1)x_3}=\frac{5-(-1)}{6}=1$$

y tenemos
$$p_3(x)=p_2(x)+1(x(x+1)(x+2))=2-3x+(x^3+3x^2+2x)=x^3+3x^2-x+2$$

Rem: Si conocieramos los valores de las constantes $c_i$, podemos ir haciendo la construcción inversa.
$$p_n(x)=p_{n-1}(x)+c_n\prod_{i=0}^{n-1}(x-x_i)=p_{n-2}(x)+c_{n-1}\prod_{i=0}^{n-2}(x-x_i)+c_n\prod_{i=0}^{n-1}(x-x_i)$$

Pero esto podemos escribir como
$$p_n(x)=p_{n-2}(x)+\prod_{i=0}^{n-2}(x-x_i)(c_{n-1}+c_n(x-x_{n-1}))$$

Si hacemos una iteración más
$$p_n(x)=p_{n-3}(x)+\prod_{i=0}^{n-3}(x-x_i)\left[c_{n-2}+(x-x_{n-2})[c_{n-1}+c_n(x-x_{n-1})]\right]$$

Y podemos tener 
$$p_n(x)=\sum_{i=0}^{n-1}c_i\prod_{j=0}^{i-1}(x-x_j)$$

considerando $p_0(x)=y_0=c_0$

Veamos esta formulita


Tenemos nosotros los valores de $c_0=8$, $c_1=-3$, $c_2=0$ y $c_3=1$

Entonces tenemos
* $8$
* $8-3(x+2)=2-3x$
* $2-3x+0(x+2)(x+1)=2-3x$
* $2-3x+1(x+2)(x+1)x=x^3+3x^2-x+2$

* 1
* $1(x)+0=x$
* $x(x+1)-3=x^2+x-3$
* $(x^2+x-3)(x+2)+8=x^3+3x^2-x-6+8=x^3+3x^2-x+2$

Tarea: Calcular el polinomio de interpolación por los 3 métodos vistos en clase

In [1]:
import numpy as np
def PoliInt(x,y):
    n=len(x)
    A=np.zeros((n,n))
    for i in range(n):
        A[:,n-1-i]=x**i
    print(A)
    a=np.linalg.solve(A,y)
    return a      

In [2]:
x=np.array([1,2,0])
y=np.array([-1,3,5])
x
y

array([-1,  3,  5])

In [3]:
PoliInt(x,y)

[[1. 1. 1.]
 [4. 2. 1.]
 [0. 0. 1.]]


array([  5., -11.,   5.])

In [4]:
x=np.array([1,2,0])
y=np.array([1,3,5])

In [5]:
PoliInt(x,y)

[[1. 1. 1.]
 [4. 2. 1.]
 [0. 0. 1.]]


array([ 3., -7.,  5.])

In [6]:
x=np.array([1,2,0,3])
y=np.array([-1,3,5,4])

In [7]:
PoliInt(x,y)

[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [ 0.  0.  0.  1.]
 [27.  9.  3.  1.]]


array([ -2.16666667,  11.5       , -15.33333333,   5.        ])